/**
 * Generated by orval 🍺
 * Do not edit manually.
 * low cost flight
 * OpenAPI spec version: 1.0.0
 */

/**
 * the collection of errors for the current context
 */
export type FastEndpointsErrorResponseErrors = { [key: string]: string[] };
