/**
 * Generated by orval 🍺
 * Do not edit manually.
 * low cost flight
 * OpenAPI spec version: 1.0.0
 */
import type { FastEndpointsErrorResponseErrors } from './fastEndpointsErrorResponseErrors';

/**
 * the dto used to send an error response to the client
 */
export interface FastEndpointsErrorResponse {
  /** the http status code sent to the client. default is 400. */
  statusCode?: number;
  /** the message for the error response */
  message?: string;
  /** the collection of errors for the current context */
  errors?: FastEndpointsErrorResponseErrors;
}
