/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */

/**
 * the collection of errors for the current context
 */
export type FastEndpointsErrorResponseErrors = {[key: string]: string[]};
