/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */

export * from './fastEndpointsErrorResponse';
export * from './fastEndpointsErrorResponseErrors';
export * from './lowCostFlightAuthCommonAuthResponse';
export * from './lowCostFlightAuthCommonUserDto';
export * from './lowCostFlightAuthGoogleLoginGoogleLoginRequest';
export * from './lowCostFlightAuthLoginLoginRequest';
export * from './lowCostFlightAuthRegisterRegisterRequest';
export * from './lowCostFlightFlightsCreateFlightDealCreateFlightDealRequest';
export * from './lowCostFlightFlightsCreateFlightDealCreateFlightDealResponse';
export * from './lowCostFlightFlightsDeleteFlightDealDeleteFlightDealRequest';
export * from './lowCostFlightFlightsGetAllFlightDealsFlightDealDto';
export * from './lowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpointParams';
export * from './lowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsRequest';
export * from './lowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsResponse';
export * from './lowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdRequest';
export * from './lowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdResponse';
export * from './lowCostFlightFlightsSearchFlightsFlightDealItem';
export * from './lowCostFlightFlightsSearchFlightsSearchFlightsEndpointParams';
export * from './lowCostFlightFlightsSearchFlightsSearchFlightsRequest';
export * from './lowCostFlightFlightsSearchFlightsSearchFlightsResponse';
export * from './lowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest';
export * from './lowCostFlightFlightsUpdateFlightDealUpdateFlightDealResponse';
export * from './microsoftAspNetCoreMvcProblemDetails';
