/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */

export type LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpointParams = {
/**
 * @nullable
 */
departureAirport?: string | null;
/**
 * @nullable
 */
arrivalAirport?: string | null;
/**
 * @nullable
 */
maxPrice?: number | null;
};
