/**
 * Generated by orval 🍺
 * Do not edit manually.
 * low cost flight
 * OpenAPI spec version: 1.0.0
 */

export interface LowCostFlightFlightsDeleteFlightDealDeleteFlightDealRequest {
  [key: string]: unknown;
}
