/**
 * Generated by orval 🍺
 * Do not edit manually.
 * low cost flight
 * OpenAPI spec version: 1.0.0
 */

export interface LowCostFlightFlightsUpdateFlightDealUpdateFlightDealResponse {
  id?: number;
  departureAirport?: string;
  arrivalAirport?: string;
  nameCity?: string;
  country?: string;
  price?: number;
  averagePrice?: number;
  discountPercentage?: number;
  currency?: string;
  durationInMinutes?: number;
  airline?: string;
  flightLink?: string;
  description?: string;
  stops?: number;
  createdAt?: string;
}
