/**
 * Generated by orval 🍺
 * Do not edit manually.
 * low cost flight
 * OpenAPI spec version: 1.0.0
 */
import type { LowCostFlightFlightsGetAllFlightDealsFlightDealDto } from './lowCostFlightFlightsGetAllFlightDealsFlightDealDto';

export interface LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsResponse {
  deals?: LowCostFlightFlightsGetAllFlightDealsFlightDealDto[];
}
