/**
 * Generated by orval 🍺
 * Do not edit manually.
 * low cost flight
 * OpenAPI spec version: 1.0.0
 */
import type { LowCostFlightFlightsSearchFlightsFlightDealItem } from './lowCostFlightFlightsSearchFlightsFlightDealItem';

export interface LowCostFlightFlightsSearchFlightsSearchFlightsResponse {
  deals?: LowCostFlightFlightsSearchFlightsFlightDealItem[];
}
