/**
 * Generated by orval 🍺
 * Do not edit manually.
 * low cost flight
 * OpenAPI spec version: 1.0.0
 */

export type LowCostFlightFlightsSearchFlightsSearchFlightsEndpointParams = {
departureId: string;
/**
 * @nullable
 */
arrivalId?: string | null;
/**
 * @nullable
 */
currency?: string | null;
/**
 * @nullable
 */
outboundDate?: string | null;
/**
 * @nullable
 */
returnDate?: string | null;
/**
 * @nullable
 */
maxPrice?: number | null;
/**
 * @nullable
 */
hl?: string | null;
/**
 * @nullable
 */
gl?: string | null;
/**
 * @nullable
 */
stops?: number | null;
};
