/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */
import type { LowCostFlightFlightsGetAllFlightDealsFlightDealDto } from './lowCostFlightFlightsGetAllFlightDealsFlightDealDto';

export interface LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsResponse {
  deals?: LowCostFlightFlightsGetAllFlightDealsFlightDealDto[];
}
