/**
 * Generated by orval 🍺
 * Do not edit manually.
 * low cost flight
 * OpenAPI spec version: 1.0.0
 */

export type LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpointParams = {
/**
 * @nullable
 */
departureAirport?: string | null;
/**
 * @nullable
 */
arrivalAirport?: string | null;
/**
 * @nullable
 */
maxPrice?: number | null;
};
