/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */

export interface LowCostFlightAuthRegisterRegisterRequest {
  /**
   * @minLength 1
   * @pattern ^[^@]+@[^@]+$
   */
  email: string;
  /** @minLength 6 */
  password: string;
  /**
   * @minLength 0
   * @maxLength 150
   */
  fullName: string;
}
