/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */

export interface LowCostFlightFlightsSearchFlightsFlightDealItem {
  departureAirport?: string;
  arrivalAirport?: string;
  nameCity?: string;
  country?: string;
  averagePrice?: number;
  discountPercentage?: number;
  price?: number;
  currency?: string;
  durationInMinutes?: number;
  airline?: string;
  flightLink?: string;
  description?: string;
  stops?: number;
}
