/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */

export interface LowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdRequest { [key: string]: unknown }
