/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */
import type { LowCostFlightFlightsSearchFlightsFlightDealItem } from './lowCostFlightFlightsSearchFlightsFlightDealItem';

export interface LowCostFlightFlightsSearchFlightsSearchFlightsResponse {
  deals?: LowCostFlightFlightsSearchFlightsFlightDealItem[];
}
