/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */

export interface LowCostFlightAuthLoginLoginRequest {
  /**
     * @minLength 1
     * @pattern ^[^@]+@[^@]+$
     */
  email: string;
  /** @minLength 1 */
  password: string;
}
