/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */

export interface LowCostFlightAuthCommonUserDto {
  id?: string;
  email?: string;
  fullName?: string;
  /** @nullable */
  pictureUrl?: string | null;
  role?: string;
}
