/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SkyDealRadar API
 * OpenAPI spec version: v1
 */
import { HttpClient } from '@angular/common/http';
import type { HttpContext, HttpEvent, HttpParams } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import type { Observable } from 'rxjs';

import type {
  LowCostFlightAuthCommonAuthResponse,
  LowCostFlightAuthCommonUserDto,
  LowCostFlightAuthGoogleLoginGoogleLoginRequest,
  LowCostFlightAuthLoginLoginRequest,
  LowCostFlightAuthRegisterRegisterRequest,
  LowCostFlightFlightsCreateFlightDealCreateFlightDealRequest,
  LowCostFlightFlightsCreateFlightDealCreateFlightDealResponse,
  LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpointParams,
  LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsResponse,
  LowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdResponse,
  LowCostFlightFlightsSearchFlightsSearchFlightsEndpointParams,
  LowCostFlightFlightsSearchFlightsSearchFlightsResponse,
  LowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest,
  LowCostFlightFlightsUpdateFlightDealUpdateFlightDealResponse,
} from './models';

import type { HttpHeaders, HttpResponse as AngularHttpResponse } from '@angular/common/http';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
    HttpParams | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value
        .filter(
          (item) =>
            item != null &&
            (typeof item === 'string' ||
              typeof item === 'number' ||
              typeof item === 'boolean' ||
              (item instanceof Date && !Number.isNaN(item.getTime()))),
        )
        .map((item) => (item instanceof Date ? item.toISOString() : item)) as Array<
        string | number | boolean
      >;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (value instanceof Date && !Number.isNaN(value.getTime())) {
      // useDates produces Date query params; serialize to ISO so they reach
      // the wire instead of being dropped by the primitive check below. See #3856.
      filteredParams[key] = value.toISOString();
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}

@Injectable({ providedIn: 'root' })
export class SkyDealRadarAPIService {
  private readonly http = inject(HttpClient);
  /**
   * Modifica i dati di un'offerta volo salvata nel database
   * @summary Aggiorna un'offerta volo esistente
   */
  lowCostFlightFlightsUpdateFlightDealUpdateFlightDealEndpoint<
    TData = LowCostFlightFlightsUpdateFlightDealUpdateFlightDealResponse,
  >(
    id: number,
    lowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest: LowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  lowCostFlightFlightsUpdateFlightDealUpdateFlightDealEndpoint<
    TData = LowCostFlightFlightsUpdateFlightDealUpdateFlightDealResponse,
  >(
    id: number,
    lowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest: LowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  lowCostFlightFlightsUpdateFlightDealUpdateFlightDealEndpoint<
    TData = LowCostFlightFlightsUpdateFlightDealUpdateFlightDealResponse,
  >(
    id: number,
    lowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest: LowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  lowCostFlightFlightsUpdateFlightDealUpdateFlightDealEndpoint<
    TData = LowCostFlightFlightsUpdateFlightDealUpdateFlightDealResponse,
  >(
    id: number,
    lowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest: LowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.put<TData>(
        `/api/flight-deals/${id}`,
        lowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'events',
        },
      );
    }

    if (options?.observe === 'response') {
      return this.http.put<TData>(
        `/api/flight-deals/${id}`,
        lowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'response',
        },
      );
    }

    return this.http.put<TData>(
      `/api/flight-deals/${id}`,
      lowCostFlightFlightsUpdateFlightDealUpdateFlightDealRequest,
      {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      },
    );
  }

  /**
   * Cerca un'offerta volo salvata nel database per chiave primaria ID
   * @summary Recupera una singola offerta volo tramite ID
   */
  lowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdEndpoint<
    TData = LowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdResponse,
  >(id: number, options?: HttpClientBodyOptions): Observable<TData>;
  lowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdEndpoint<
    TData = LowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdResponse,
  >(id: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
  lowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdEndpoint<
    TData = LowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdResponse,
  >(id: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  lowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdEndpoint<
    TData = LowCostFlightFlightsGetFlightDealByIdGetFlightDealByIdResponse,
  >(
    id: number,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/flight-deals/${id}`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/flight-deals/${id}`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`/api/flight-deals/${id}`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  /**
   * Rimuove definitivamente un'offerta volo dalla tabella FlightDeals per ID
   * @summary Elimina un'offerta volo dal database
   */
  lowCostFlightFlightsDeleteFlightDealDeleteFlightDealEndpoint<TData = void>(
    id: number,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  lowCostFlightFlightsDeleteFlightDealDeleteFlightDealEndpoint<TData = void>(
    id: number,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  lowCostFlightFlightsDeleteFlightDealDeleteFlightDealEndpoint<TData = void>(
    id: number,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  lowCostFlightFlightsDeleteFlightDealDeleteFlightDealEndpoint<TData = void>(
    id: number,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(`/api/flight-deals/${id}`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(`/api/flight-deals/${id}`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.delete<TData>(`/api/flight-deals/${id}`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  lowCostFlightFlightsSearchFlightsSearchFlightsEndpoint<
    TData = LowCostFlightFlightsSearchFlightsSearchFlightsResponse,
  >(
    params: LowCostFlightFlightsSearchFlightsSearchFlightsEndpointParams,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  lowCostFlightFlightsSearchFlightsSearchFlightsEndpoint<
    TData = LowCostFlightFlightsSearchFlightsSearchFlightsResponse,
  >(
    params: LowCostFlightFlightsSearchFlightsSearchFlightsEndpointParams,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  lowCostFlightFlightsSearchFlightsSearchFlightsEndpoint<
    TData = LowCostFlightFlightsSearchFlightsSearchFlightsResponse,
  >(
    params: LowCostFlightFlightsSearchFlightsSearchFlightsEndpointParams,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  lowCostFlightFlightsSearchFlightsSearchFlightsEndpoint<
    TData = LowCostFlightFlightsSearchFlightsSearchFlightsResponse,
  >(
    params: LowCostFlightFlightsSearchFlightsSearchFlightsEndpointParams,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({ ...params, ...options?.params }, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/flights/search`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/flights/search`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,
      });
    }

    return this.http.get<TData>(`/api/flights/search`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
      params: filteredParams,
    });
  }

  /**
   * Restituisce l'elenco delle offerte salvate, con filtri opzionali per aeroporto e prezzo massimo
   * @summary Recupera tutte le offerte volo dal database
   */
  lowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpoint<
    TData = LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsResponse,
  >(
    params?: LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpointParams,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  lowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpoint<
    TData = LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsResponse,
  >(
    params?: LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpointParams,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  lowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpoint<
    TData = LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsResponse,
  >(
    params?: LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpointParams,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  lowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpoint<
    TData = LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsResponse,
  >(
    params?: LowCostFlightFlightsGetAllFlightDealsGetAllFlightDealsEndpointParams,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({ ...params, ...options?.params }, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/flight-deals`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/flight-deals`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,
      });
    }

    return this.http.get<TData>(`/api/flight-deals`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
      params: filteredParams,
    });
  }

  /**
   * Inserisce una nuova offerta volo con tutti i dettagli nella tabella FlightDeals
   * @summary Crea una nuova offerta volo nel database
   */
  lowCostFlightFlightsCreateFlightDealCreateFlightDealEndpoint<
    TData = LowCostFlightFlightsCreateFlightDealCreateFlightDealResponse,
  >(
    lowCostFlightFlightsCreateFlightDealCreateFlightDealRequest: LowCostFlightFlightsCreateFlightDealCreateFlightDealRequest,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  lowCostFlightFlightsCreateFlightDealCreateFlightDealEndpoint<
    TData = LowCostFlightFlightsCreateFlightDealCreateFlightDealResponse,
  >(
    lowCostFlightFlightsCreateFlightDealCreateFlightDealRequest: LowCostFlightFlightsCreateFlightDealCreateFlightDealRequest,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  lowCostFlightFlightsCreateFlightDealCreateFlightDealEndpoint<
    TData = LowCostFlightFlightsCreateFlightDealCreateFlightDealResponse,
  >(
    lowCostFlightFlightsCreateFlightDealCreateFlightDealRequest: LowCostFlightFlightsCreateFlightDealCreateFlightDealRequest,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  lowCostFlightFlightsCreateFlightDealCreateFlightDealEndpoint<
    TData = LowCostFlightFlightsCreateFlightDealCreateFlightDealResponse,
  >(
    lowCostFlightFlightsCreateFlightDealCreateFlightDealRequest: LowCostFlightFlightsCreateFlightDealCreateFlightDealRequest,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
        `/api/flight-deals`,
        lowCostFlightFlightsCreateFlightDealCreateFlightDealRequest,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'events',
        },
      );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
        `/api/flight-deals`,
        lowCostFlightFlightsCreateFlightDealCreateFlightDealRequest,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'response',
        },
      );
    }

    return this.http.post<TData>(
      `/api/flight-deals`,
      lowCostFlightFlightsCreateFlightDealCreateFlightDealRequest,
      {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      },
    );
  }

  lowCostFlightAuthRegisterRegisterEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthRegisterRegisterRequest: LowCostFlightAuthRegisterRegisterRequest,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  lowCostFlightAuthRegisterRegisterEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthRegisterRegisterRequest: LowCostFlightAuthRegisterRegisterRequest,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  lowCostFlightAuthRegisterRegisterEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthRegisterRegisterRequest: LowCostFlightAuthRegisterRegisterRequest,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  lowCostFlightAuthRegisterRegisterEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthRegisterRegisterRequest: LowCostFlightAuthRegisterRegisterRequest,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/api/auth/register`, lowCostFlightAuthRegisterRegisterRequest, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/api/auth/register`, lowCostFlightAuthRegisterRegisterRequest, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.post<TData>(`/api/auth/register`, lowCostFlightAuthRegisterRegisterRequest, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  lowCostFlightAuthLoginLoginEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthLoginLoginRequest: LowCostFlightAuthLoginLoginRequest,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  lowCostFlightAuthLoginLoginEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthLoginLoginRequest: LowCostFlightAuthLoginLoginRequest,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  lowCostFlightAuthLoginLoginEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthLoginLoginRequest: LowCostFlightAuthLoginLoginRequest,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  lowCostFlightAuthLoginLoginEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthLoginLoginRequest: LowCostFlightAuthLoginLoginRequest,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/api/auth/login`, lowCostFlightAuthLoginLoginRequest, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/api/auth/login`, lowCostFlightAuthLoginLoginRequest, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.post<TData>(`/api/auth/login`, lowCostFlightAuthLoginLoginRequest, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  lowCostFlightAuthGoogleLoginGoogleLoginEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthGoogleLoginGoogleLoginRequest: LowCostFlightAuthGoogleLoginGoogleLoginRequest,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  lowCostFlightAuthGoogleLoginGoogleLoginEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthGoogleLoginGoogleLoginRequest: LowCostFlightAuthGoogleLoginGoogleLoginRequest,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  lowCostFlightAuthGoogleLoginGoogleLoginEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthGoogleLoginGoogleLoginRequest: LowCostFlightAuthGoogleLoginGoogleLoginRequest,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  lowCostFlightAuthGoogleLoginGoogleLoginEndpoint<TData = LowCostFlightAuthCommonAuthResponse>(
    lowCostFlightAuthGoogleLoginGoogleLoginRequest: LowCostFlightAuthGoogleLoginGoogleLoginRequest,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
        `/api/auth/google`,
        lowCostFlightAuthGoogleLoginGoogleLoginRequest,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'events',
        },
      );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
        `/api/auth/google`,
        lowCostFlightAuthGoogleLoginGoogleLoginRequest,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'response',
        },
      );
    }

    return this.http.post<TData>(
      `/api/auth/google`,
      lowCostFlightAuthGoogleLoginGoogleLoginRequest,
      {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      },
    );
  }

  lowCostFlightAuthGetMeGetMeEndpoint<TData = LowCostFlightAuthCommonUserDto>(
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  lowCostFlightAuthGetMeGetMeEndpoint<TData = LowCostFlightAuthCommonUserDto>(
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  lowCostFlightAuthGetMeGetMeEndpoint<TData = LowCostFlightAuthCommonUserDto>(
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  lowCostFlightAuthGetMeGetMeEndpoint<TData = LowCostFlightAuthCommonUserDto>(
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/auth/me`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/auth/me`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`/api/auth/me`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }
}

export { SkyDealRadarAPIService as LowCostFlightService };
